Task 5 dependency injection
manganian/invoicing-system-dawid-chojnacki pull request #12
Opened 2022-09-03 14:32 UTC by manganian

2022-09-05 18:01 UTC, patryk-stepniak requested changes
Kilka uwag

2022-09-05 18:01 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/memory/InMemoryDatabase.java
>  public class InMemoryDatabase implements Database {
Definiowanie beanów baz danych na dwa różne sposoby może być mylące.
Lepiej trzymać się jednego rozwiązania.
Szczególnie, że widząc klasę DatabaseConfiguration naturalnym jest, że spodziewam się tam znaleźć całą konfigurację.

2022-09-07 07:18 UTC, patryk-stepniak requested changes
Bardzo fajnie to wygląda.

Tylko jedna rzecz do poprawy.

2022-09-07 07:18 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/config/InvoiceConfiguration.java
> +  public static final String INVOICES_FILE_NAME = "invoices.json";
Te pola powinny być prywatne.

2022-09-07 16:45 UTC, manganian commented on src/main/java/pl/futurecollars/invoicing/config/InvoiceConfiguration.java
> +  public static final String INVOICES_FILE_NAME = "invoices.json";
Done

2022-09-08 06:22 UTC, patryk-stepniak requested changes
Jedna uwaga

2022-09-08 06:22 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/service/InvoiceService.java
> +  @Autowired
Ta adnotacja nie jest potrzebna skoro tworzymy ten obiekt przez klasę konfiguracyjną.

2022-09-08 08:22 UTC, manganian commented on src/main/java/pl/futurecollars/invoicing/service/InvoiceService.java
> +  @Autowired
Done

2022-09-08 18:15 UTC, patryk-stepniak approved these changes

2022-09-08 18:15 UTC, merged