Task 7.2 spring profiles logger
manganian/invoicing-system-dawid-chojnacki pull request #29
Opened 2022-09-29 14:18 UTC by RadBor200

2022-09-29 15:26 UTC, patryk-stepniak requested changes
Dwie rzeczy do poprawy

2022-09-29 15:26 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/db/file/IdService.java
> +        // inicjalizujemy id database wartocia 1
a co to to to? ;>

2022-09-29 15:26 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/config/InvoiceConfiguration.java
>  public class InvoiceConfiguration {
jsonService oraz filesService powinny być tworzone tylko wtedy, gdy mamy aktywny odpowiedni profil. Analogicznie do fileBasedDatabase

2022-09-29 15:26 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/config/InvoiceConfiguration.java
>  public class InvoiceConfiguration {
+ konflikty

2022-09-29 16:10 UTC, manganian commented on src/main/java/pl/futurecollars/invoicing/config/InvoiceConfiguration.java
>    @Bean
A nie chodziło o to, aby jsonService i fileService miał linijke @ConditionalOnProperty(name = "database.type", havingValue = "file")

2022-09-29 16:17 UTC, manganian approved these changes

2022-09-29 16:58 UTC, manganian requested changes

2022-09-29 16:58 UTC, manganian commented on src/main/java/pl/futurecollars/invoicing/config/InvoiceConfiguration.java
IdService jeszcze potrzebuje tej linijki. @ConditionalOnProperty(name = "database.type", havingValue = "file")
Bez tego apka nie działa na profilu dev.

2022-09-29 22:32 UTC, manganian approved these changes

2022-10-03 14:48 UTC, patryk-stepniak approved these changes

2022-10-03 14:49 UTC, merged