Task 9.1 dc tax calculator
manganian/invoicing-system-dawid-chojnacki pull request #34
Opened 2022-09-29 18:10 UTC by manganian

2022-10-02 13:10 UTC, OtonashiKanata approved these changes

2022-10-03 15:12 UTC, patryk-stepniak requested changes
Kilka uwag

2022-10-03 15:12 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/service/TaxCalculatorResult.java
> +  private final BigDecimal income;
@ApiModelProperty

2022-10-03 15:12 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/service/TaxCalculatorService.java
> +  public BigDecimal income(String taxIdentificationNumber) {
Dlaczego te pola są publiczne?
Pamiętajcie o kolejności metod.

2022-10-03 15:12 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/service/TaxCalculatorService.java
> +  public BigDecimal getEarnings(String taxIdentificationNumber) {
Niektóre z metod zaczynają się od get, inne nie - pomimo, że mogłyby.

2022-10-03 15:13 UTC, patryk-stepniak commented
Branch wymaga update'u.

2022-10-03 15:39 UTC, RadBor200 approved these changes

2022-10-05 03:48 UTC, OtonashiKanata approved these changes

2022-10-05 08:10 UTC, patryk-stepniak approved these changes

2022-10-05 08:10 UTC, merged