Task 4 spring boot and rest
manganian/invoicing-system-dawid-chojnacki pull request #8
Opened 2022-08-28 09:32 UTC by manganian

2022-08-30 17:17 UTC, patryk-stepniak requested changes
Kilka drobnych uwag

2022-08-30 17:17 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/controller/InvoiceController.java
> +  InvoiceService invoiceService = new InvoiceService(new InMemoryDatabase());
Niepotrzebnie package-private.

2022-08-30 17:17 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/controller/InvoiceController.java
> +  @PostMapping()
Niepotrzebne nawiasy

2022-08-30 17:17 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/controller/InvoiceController.java
> +  @GetMapping ("/{id}")
Losowa spacja przed nawiasem

2022-08-30 17:17 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/controller/InvoiceController.java
> +    if (invoiceService.getById(id).isPresent()) {
Lepiej będzie jak sprawdzanie wyniesiesz do service'u - tam umieszczamy logikę biznesową.
Metoda delete mogła by zwracać true/false i na tej podstawie będziesz zwracał odpowiednią odpowiedź.

2022-08-30 17:17 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/controller/InvoiceController.java
> +    if (invoiceService.getById(id).isPresent()) {
jak wyżej

2022-08-30 17:17 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoicing/controller/InvoiceController.java
> +    return ResponseEntity.ok(invoiceService.save(invoice));
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201

2022-09-03 17:01 UTC, patryk-stepniak requested changes
Cały czas pozostaje kwestia pola InvoiceService w InvoiceController.

2022-09-03 18:35 UTC, manganian commented on src/main/java/pl/futurecollars/invoicing/controller/InvoiceController.java
> +  InvoiceService invoiceService = new InvoiceService(new InMemoryDatabase());
done

2022-09-05 17:24 UTC, patryk-stepniak approved these changes

2022-09-05 17:24 UTC, merged